### ISSUE TITLE
Channel entries API

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine-User-Guide#244]
**Suggested Change**

Guys, is it possible to bring the Channel Entries API back?

**Reasoning**
I can't found it, but I really need it.

**Comment by intoeetive** [comment]
The documentaion is missing indeed - I'm not sure what has been the reason to remove it, probably just to encourage people to use Model service. There is documentation for v4 though, and I think you can just use it as the library did not change since: https://docs.expressionengine.com/v4/development/legacy/api/api_channel_entries.html

The legacy library is still there, but please note that it's going to be deprecated and then removed one day. We also can't really promise (since it's legacy) that certain future changes to ChannelEntry model will be compatible with it.

**Comment by robsonsobral** [comment]
I'm sorry, @intoeetive ! I've found the reason for it: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/issues/17

This is what is missing: https://github.com/blairliikala/ExpressionEngine-User-Guide/blob/6.dev/docs/development/models/channel-entry.md
