### ISSUE TITLE
A search of entry_id does not bring back the Channel page

### ISSUE THREAD

**Issue by nep** [ExpressionEngine/ExpressionEngine-User-Guide#26]
**Description of the problem**
Typing "entry_id" into the search box brings back 5 pages, but none of them are the Channel entries page, which I think should definitely be on this returned list.  Then, pressing "enter" after this brings you to the "Comment Subscriptions" page, so there's no result page that shows you the actual content you might be looking for.

<img width="567" alt="screenshot 2019-02-07 01 33 08" src="https://user-images.githubusercontent.com/49483/52399168-940f8d00-2a78-11e9-8e1f-27f6761ee348.png">

**Comment by Jordan-Ellis** [comment]
Hi Travis, I'll look into making the channel entries page higher in priority over the other ones.

When pressing enter, the search will take you to the highlighted item in the search results. This is the expected behavior. DocSearch also does not have a dedicated search results page, do to the nature of its real-time results.

**Comment by nep** [comment]
Hi, Jordan.

If you're going to look into making the Channel Entries page show up higher in the results, then can you leave this issue open until you or someone else has done so and either resolved it or concluded it's not possible?

On the other hand, if you feel this isn't a bug, then I'm fine with closing it.

The fact that DocSearch doesn't use a results page, I'm fine with ignoring that aspect of this report, now that I understand why it's the case.
