### ISSUE TITLE
When you submit a search with enter, the search term is erased from the search box

### ISSUE THREAD

**Issue by nep** [ExpressionEngine/ExpressionEngine-User-Guide#27]
**Description of the problem**
When you do a search and click enter or select a page, the search term is erased from the search box on the destination page. This makes it hard to revise your search, or even remember what your search was, if you have a short attention span.

**Additional context**
I think the preferred behavior should be to keep the search term in the search box. Perhaps you could set a cookie with the last search text, or store it in a session variable.

**Comment by Jordan-Ellis** [comment]
Hi Travis, this is the expected behavior. We don’t control DocSearch’s API, and it’s not intended to persist the search term across pages because of the real-time results.

**Comment by nep** [comment]
Hi, Jordan.  Thanks for your reply.

"this is the expected behavior" -- Just because it's what you as the developer expect to happen given your knowledge of the oddities/limitations of the tool -- that doesn't mean it's not a bug, nor does it mean that's the behavior that people other than yourself will expect.

I think it's pretty likely not expected behavior for a search results page to not have the search terms used to get there be both **visible** and **quickly modifiable** in order to allow the start a related search (and/or also to redo the same search and choose a different result, given that there's no results page to return to.) 

Having the search box retain the last search is not an unexpected or novel approach to search UI.  Helping someone to not have to retype a longer string to search again, or to be able to add another word to the search to further refine the results, these are common and important user behaviors.

If the goal of using DocSearch is to improve the searchability of the docs (which I think is the overall goal) then getting the UX to work optimally and in line with best practices, is an important aspect of that.

I respectfully request that you re-open this issue.

**Comment by Jordan-Ellis** [comment]
There are multiple problems with making the search retain state, most importantly, the solutions require API access we don't have.

One way is to keep the search term in the url which would populate the search input. This is how most search inputs work which have a dedicated results page. This would be an easy solution but there's no way to access the search result links that DocSearch returns, so it's not possible. It also means that links could have unwanted search terms when sharing them.

The other way is to use a one-time cookie that returns the search term until the next page load. This, however, is also not possible since there's no way of knowing if the user has clicked on a search result from the DocSearch menu. Any other potential solution would be very hacky and create unexpected behavior.

Keeping the search term in the input could also create other usability problems.  In many cases, you might change your search term completely meaning you'll have to delete the term before typing. No product I'm aware of that uses DocSearch (jQuery,  react, bootstrap) behaves this way, and many websites do not retain the term either. I'm not saying this behavior is correct, there's just no good solution for it. The bottom line is that this is a feature that would have to be implemented by DocSearch.
